export const doctors = [
  {
    id: "d1",
    name: "Dr. Ayesha Rahman",
    specialty: "Cardiologist",
    image: "/Dr.AyeshaRahman.png",
    rating: 4.9,
    reviews: 120,
    hospital: "Labaid Cardiac Hospital",
    location: "Dhanmondi, Dhaka",
    fee: 800,
    experience: "10 years",
    description: "Highly experienced cardiologist specializing in heart diseases, preventive care, and patient-centered treatment.",
    availability: ["09:00 AM - 12:00 PM", "04:00 PM - 07:00 PM"],
  },
  {
    id: "d2",
    name: "Dr. Rafiq Ahmed",
    specialty: "Dermatologist",
    image: "/Dr.RafiqAhmed.png",
    rating: 4.8,
    reviews: 98,
    hospital: "Evercare Hospital",
    location: "Bashundhara, Dhaka",
    fee: 1000,
    experience: "8 years",
    description: "Expert dermatologist treating skin, hair, and nail disorders with advanced technological solutions.",
    availability: ["10:00 AM - 01:00 PM", "05:00 PM - 08:00 PM"],
  },
  {
    id: "d3",
    name: "Dr. Sharmeen Akter",
    specialty: "Neurologist",
    image: "/Dr.SharmeenAkter.png",
    rating: 4.7,
    reviews: 88,
    hospital: "BIRDEM Hospital",
    location: "Shahbagh, Dhaka",
    fee: 1200,
    experience: "12 years",
    description: "Specialized in treating neurological conditions, brain disorders, and providing comprehensive nerve care.",
    availability: ["08:00 AM - 11:00 AM", "03:00 PM - 06:00 PM"],
  },
  {
    id: "d4",
    name: "Dr. Imran Uddin",
    specialty: "Orthopedic Surgeon",
    image: "/Dr.ImranUddin.png",
    rating: 4.6,
    reviews: 150,
    hospital: "Square Hospital",
    location: "Panthapath, Dhaka",
    fee: 1500,
    experience: "15 years",
    description: "Renowned orthopedic surgeon specializing in joint replacements, sports injuries, and complex trauma surgeries.",
    availability: ["04:00 PM - 08:00 PM"],
  },
  {
    id: "d5",
    name: "Dr. Mahfuzul Haque",
    specialty: "Pediatrician",
    image: "/Dr.MahfuzulHaque.png",
    rating: 4.9,
    reviews: 210,
    hospital: "Dhaka Shishu Hospital",
    location: "Sher-e-Bangla Nagar, Dhaka",
    fee: 700,
    experience: "14 years",
    description: "Compassionate pediatrician dedicated to infant, child, and adolescent healthcare, including immunizations and nutrition.",
    availability: ["09:00 AM - 01:00 PM", "05:00 PM - 09:00 PM"],
  },
  {
    id: "d6",
    name: "Dr. Nadia Sultana",
    specialty: "Gynecologist",
    image: "/Dr.NadiaSultana.png",
    rating: 4.8,
    reviews: 175,
    hospital: "Popular Diagnostic Centre",
    location: "Mirpur, Dhaka",
    fee: 1000,
    experience: "9 years",
    description: "Expert in women's reproductive health, prenatal care, and advanced gynecological surgeries.",
    availability: ["11:00 AM - 02:00 PM", "06:00 PM - 09:00 PM"],
  },
  {
    id: "d7",
    name: "Dr. Nushrat Jahan",
    specialty: "Psychiatrist",
    image: "/Dr.NushratJahan.png",
    rating: 4.7,
    reviews: 65,
    hospital: "Ibn Sina Hospital",
    location: "Dhanmondi, Dhaka",
    fee: 1200,
    experience: "7 years",
    description: "Dedicated psychiatrist focusing on mental health, anxiety, depression, and cognitive behavioral therapy.",
    availability: ["03:00 PM - 07:00 PM"],
  },
  {
    id: "d8",
    name: "Dr. Shahriar Alam",
    specialty: "General Surgeon",
    image: "/Dr.ShahriarAlam.png",
    rating: 4.5,
    reviews: 112,
    hospital: "United Hospital",
    location: "Gulshan, Dhaka",
    fee: 1500,
    experience: "18 years",
    description: "Highly skilled general surgeon with extensive experience in minimally invasive laparoscopic procedures.",
    availability: ["08:00 AM - 12:00 PM"],
  }
];